CREATE DATABASE forum;
USE forum;
CREATE TABLE usuarios (id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL,email VARCHAR(200) NOT NULL UNIQUE,senha VARCHAR(255) NOT NULL,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE topicos (id INT AUTO_INCREMENT PRIMARY KEY,titulo VARCHAR(255) NOT NULL,conteudo TEXT NOT NULL,user_id INT NOT NULL,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES usuarios(id));
CREATE TABLE respostas (id INT AUTO_INCREMENT PRIMARY KEY,topico_id INT NOT NULL,conteudo TEXT NOT NULL,user_id INT NOT NULL,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (topico_id) REFERENCES topicos(id),FOREIGN KEY (user_id) REFERENCES usuarios(id));
